//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

use sea_orm::entity::prelude::*;
use sea_orm::EntityTrait;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, EnumIter, DeriveActiveEnum, Deserialize, Serialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "String(Some(5))",
    enum_name = "tag_entity_type"
)]
pub enum EntityType {
    #[sea_orm(string_value = "AG")]
    ActionGroup,
    #[sea_orm(string_value = "TC")]
    S3,
    #[sea_orm(string_value = "TS")]
    TestSuit,
}

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Deserialize, Serialize)]
#[sea_orm(table_name = "tag_entity")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: Uuid,
    pub tag_id: Uuid,
    pub entity_id: Uuid,
    pub entity_type: EntityType,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
