//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0
//! Config will have all the Orca Configuration

use sea_orm::entity::prelude::*;
use sea_orm::EntityTrait;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, EnumIter, DeriveActiveEnum, Deserialize, Serialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "String(Some(5))",
    enum_name = "config_key"
)]
pub enum ConfigType {
    #[sea_orm(string_value = "AttachmentType")]
    AttachmentType,
    #[sea_orm(string_value = "Logging")]
    Logging,
}

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Deserialize, Serialize)]
#[sea_orm(table_name = "config")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub key: ConfigType,
    pub reference_id: serde_json::Value,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
