//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

pub use super::common::attachment;
pub use super::test::ui::{
    action::{group, target},
    case::{case, case_block, data_binding},
};
pub use super::test::ui::{
    action::{group::Entity as ActionGroup, target::Entity as ActionTarget},
    case::{
        case::Entity as Case, case_block::Entity as CaseBlock, data_binding::Entity as DataBinding,
    },
};
