export const ActionKind = [
  { label: "Enter", key: "Enter" },
  { label: "Click", key: "Click" },
  { label: "Open", key: "Open" },
  { label: "Double Click", key: "DoubleClick" },
  { label: "ClickAt", key: "ClickAt" },
  { label: "Double ClickAt", key: "DoubleClickAt" },
  { label: "DragAndDropToObject", key: "DragAndDropToObject" },
  { label: "Execute Script", key: "ExecuteScript" },
  { label: "MouseDown", key: "MouseDown" },
  { label: "MouseDownAt", key: "MouseDownAt" },
  { label: "MouseMove", key: "MouseMove" },
  { label: "MouseMoveAt", key: "MouseMoveAt" },
  { label: "MouseOver", key: "MouseOver" },
  { label: "MouseOut", key: "MouseOut" },
  { label: "MouseUp", key: "MouseUp" },
  { label: "MouseUpAt", key: "MouseUpAt" },
  { label: "Select", key: "Select" },
  { label: "Select Frame", key: "SelectFrame" },
  { label: "Select Window", key: "SelectWindow" },
  { label: "Send Keys", key: "SendKeys" },
  { label: "Submit", key: "Submit" },
  { label: "Uncheck", key: "Uncheck" },
  { label: "Verify", key: "Verify" },
  { label: "Verify Checked", key: "VerifyChecked" },
  { label: "Verify Editable", key: "VerifyEditable" },
  { label: "Verify ElementPresent", key: "VerifyElementPresent" },
  { label: "Verify NotChecked", key: "VerifyNotChecked" },
  { label: "Verify NotEditable", key: "VerifyNotEditable" },
  { label: "Verify Text", key: "VerifyText" },
  { label: "Verify Title", key: "VerifyTitle" },
  { label: "Verify Value", key: "VerifyValue" },
  { label: "WaitForElementVisible", key: "WaitForElementVisible" },
  {
    label: "WebDriverAnswerOnVisiblePrompt",
    key: "WebDriverAnswerOnVisiblePrompt"
  },
  {
    label: "WebDriverChooseCancelOnVisiblePrompt",
    key: "WebDriverChooseCancelOnVisiblePrompt"
  }
];
