//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

use sea_orm::entity::prelude::*;
use sea_orm::EntityTrait;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, EnumIter, DeriveActiveEnum, Deserialize, Serialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "String(Some(15))",
    enum_name = "action_group_kind"
)]
pub enum ActionGroupKind {
    #[sea_orm(string_value = "ActionGroup")]
    ActionGroup,
    #[sea_orm(string_value = "Assertion")]
    Assertion,
}

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Deserialize, Serialize)]
#[sea_orm(table_name = "action_group")]
pub struct Model {
    #[serde(skip_deserializing)]
    #[sea_orm(primary_key)]
    pub id: Uuid,
    pub name: String,
    pub description: Option<String>,
    #[sea_orm(column_name = "type")]
    pub type_field: ActionGroupKind,
    #[serde(skip_deserializing)]
    pub app_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::action::Entity")]
    Action,
    #[sea_orm(
        belongs_to = "crate::app::app::Entity",
        from = "Column::AppId",
        to = "crate::app::app::Column::Id"
    )]
    App,
}

// `Related` trait has to be implemented by hand
impl Related<super::action::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Action.def()
    }
}

impl Related<crate::app::app::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::App.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
