//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

use sea_orm::entity::prelude::*;
use sea_orm::EntityTrait;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, EnumIter, DeriveActiveEnum, Deserialize, Serialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "kind")]
pub enum ActionKind {
    #[sea_orm(string_value = "ActionGroup")]
    ActionGroup,
    #[sea_orm(string_value = "ValidationGroup")]
    ValidationGroup,
}

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Deserialize, Serialize)]
#[sea_orm(table_name = "case_block")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub execution_order: i64,
    pub kind: ActionKind,
    pub reference: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
