//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

use sea_orm::entity::prelude::*;
use sea_orm::EntityTrait;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, EnumIter, DeriveActiveEnum, Deserialize, Serialize)]
#[sea_orm(rs_type = "String", db_type = "String(Some(15))", enum_name = "block_kind")]
pub enum BlockKind {
    #[sea_orm(string_value = "Loop")]
    Loop,
    #[sea_orm(string_value = "Condition")]
    Condition,
    #[sea_orm(string_value = "Reference")]
    Reference,
    // #[sea_orm(string_value = "ValidationGroup")]
    // ValidationGroup,
}

#[derive(Debug, Clone, PartialEq, EnumIter, DeriveActiveEnum, Deserialize, Serialize)]
#[sea_orm(rs_type = "String", db_type = "String(Some(15))", enum_name = "block_type")]
pub enum BlockType {
    #[sea_orm(string_value = "InMemory")]
    InMemory,
    #[sea_orm(string_value = "DataTable")]
    DataTable,
    #[sea_orm(string_value = "ActionGroup")]
    ActionGroup,
    #[sea_orm(string_value = "ValidationGroup")]
    ValidationGroup,
}

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Deserialize, Serialize)]
#[sea_orm(table_name = "case_block")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: Uuid,
    pub execution_order: i32,
    pub kind: BlockKind,
    #[sea_orm(column_name = "type")]
    pub type_field: BlockType,
    pub reference: String,
    // pub case_id: Option<i64>,
    pub parent_id: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::data_binding::Entity")]
    DataBinding,
    #[sea_orm(belongs_to = "Entity", from = "Column::Id", to = "Column::ParentId")]
    SelfReferencing,
    #[sea_orm(
        belongs_to = "super::case::Entity",
        from = "Column::ParentId",
        to = "super::case::Column::Id"
    )]
    Case,
}

// `Related` trait has to be implemented by hand
impl Related<super::data_binding::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DataBinding.def()
    }
}

impl Related<super::case::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Case.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}


pub struct SelfReferencingLink;

impl Linked for SelfReferencingLink {
    type FromEntity = Entity;

    type ToEntity = Entity;

    fn link(&self) -> Vec<RelationDef> {
        vec![Relation::SelfReferencing.def()]
    }
}
