//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

use sea_orm::entity::prelude::*;
use sea_orm::EntityTrait;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Deserialize, Serialize)]
#[sea_orm(table_name = "case")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: Uuid,
    pub name: String,
    pub description: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::case_block::Entity")]
    CaseBlock,
}

// `Related` trait has to be implemented by hand
impl Related<super::case_block::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CaseBlock.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
